basic-stats:
  Points: 
    col: pts
  Field Goal %:
    col: fg_pct
    volume-stat: fga
    volume-stat-label: Field Goals Attempted
  Three Point %:
    col: fg3_pct
    volume-stat: fg3a
    volume-stat-label: Three Pointers Attempted
  Free Throw %:
    col: ft_pct
    volume-stat: fta
    volume-stat-label: Free Throws Attempted
  Rebounds:
    col: reb
  Assists:
    col: ast
  Steals:
    col: stl
  Blocks:
    col: blk
  Turn Overs:
    col: tov
  Minutes: 
    col: min